[
  "{ label: 'Ethereum' ,backgroundColor: EthereumColor, borderColor: EthereumColor, fill: false, data: dataEthereum,  }",
  "{ label: 'Uniswap' ,backgroundColor: UniswapColor, borderColor: UniswapColor, fill: false, data: dataUniswap,  }",
  "{ label: 'Binance_Smart_Chain' ,backgroundColor: Binance_Smart_ChainColor, borderColor: Binance_Smart_ChainColor, fill: false, data: dataBinance_Smart_Chain,  }",
  "{ label: 'Aave' ,backgroundColor: AaveColor, borderColor: AaveColor, fill: false, data: dataAave,  }",
  "{ label: 'Balancer' ,backgroundColor: BalancerColor, borderColor: BalancerColor, fill: false, data: dataBalancer,  }",
  "{ label: 'SushiSwap' ,backgroundColor: SushiSwapColor, borderColor: SushiSwapColor, fill: false, data: dataSushiSwap,  }",
  "{ label: 'Trader_Joe' ,backgroundColor: Trader_JoeColor, borderColor: Trader_JoeColor, fill: false, data: dataTrader_Joe,  }",
  "{ label: 'Bitcoin' ,backgroundColor: BitcoinColor, borderColor: BitcoinColor, fill: false, data: dataBitcoin,  }",
  "{ label: 'Compound' ,backgroundColor: CompoundColor, borderColor: CompoundColor, fill: false, data: dataCompound,  }",
  "{ label: 'SpookySwap' ,backgroundColor: SpookySwapColor, borderColor: SpookySwapColor, fill: false, data: dataSpookySwap,  }",
  "{ label: 'Abracadabra_money' ,backgroundColor: Abracadabra_moneyColor, borderColor: Abracadabra_moneyColor, fill: false, data: dataAbracadabra_money,  }",
  "{ label: 'Terraswap' ,backgroundColor: TerraswapColor, borderColor: TerraswapColor, fill: false, data: dataTerraswap,  }",
  "{ label: 'Quickswap' ,backgroundColor: QuickswapColor, borderColor: QuickswapColor, fill: false, data: dataQuickswap,  }",
  "{ label: 'MakerDAO' ,backgroundColor: MakerDAOColor, borderColor: MakerDAOColor, fill: false, data: dataMakerDAO,  }",
  "{ label: 'Avalanche' ,backgroundColor: AvalancheColor, borderColor: AvalancheColor, fill: false, data: dataAvalanche,  }",
];
